apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    name: demo-app
    app.kubernetes.io/name: demo-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: demo-app
