services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: demo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demoapp
      MYSQL_USER: demouser
      MYSQL_PASSWORD: demopassword
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      # Volume mount for persistent data
      - mysql_data:/var/lib/mysql
      # Bind mount for initialization scripts
      - ./mysql-init:/docker-entrypoint-initdb.d
      # Bind mount for MySQL configuration
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - demo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Spring Boot Application
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demoapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=demouser
      - SPRING_DATASOURCE_PASSWORD=demopassword
    volumes:
      # Bind mount for application logs
      - ./logs:/app/logs
      # Volume mount for temporary files
      - app_temp:/tmp
    networks:
      - demo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # phpMyAdmin for database management (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: demo-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - demo-network

# Named volumes for data persistence
volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/mysql-data
  app_temp:
    driver: local

# Custom network
networks:
  demo-network:
    driver: bridge